graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
    subscriptions: /subscriptions
  subscriptions:
    timeout: 30
    reconnect: false
  static:
    basePath: /
  enabled: true
  pageTitle: GraphiQL

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:32768/retool_demo?useSSL=false
    username: root
    password: password
